services:
  web-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database:27017/my-docker-db
    depends_on:
      - database

  database:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: